#!/bin/bash
PACKAGES=$(dpkg --list grml-live\* | awk '/^ii/ {print $2}')
env APT_LISTCHANGES_FRONTEND=none APT_LISTBUGS_FRONTEND=none sudo apt-get -y \
  -o DPkg::Options::=--force-confmiss \
  -o DPkg::Options::=--force-confnew  \
  --allow-unauthenticated install $PACKAGES
